# Generated by Django 3.1.6 on 2021-03-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_result_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='profile',
            field=models.ImageField(blank=True, default='static\\img\\profile.svg', null=True, upload_to=''),
        ),
    ]
