# Generated by Django 3.1.6 on 2021-03-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_auto_20210310_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='profile',
            field=models.ImageField(blank=True, default='/img/profile.svg', null=True, upload_to=''),
        ),
    ]
