# Generated by Django 3.1.6 on 2021-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_auto_20210310_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='profile',
            field=models.ImageField(blank=True, default='/media/profile.svg', null=True, upload_to='profile_pic'),
        ),
    ]
