# Generated by Django 3.1.6 on 2021-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0016_auto_20210312_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
