# Generated by Django 3.1.6 on 2021-03-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0022_auto_20210314_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
