# Generated by Django 3.1.6 on 2021-03-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0023_auto_20210314_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
