# Generated by Django 3.1.6 on 2021-03-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0026_userform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserForm',
        ),
    ]
