# Generated by Django 3.1.6 on 2021-03-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0028_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
