# Generated by Django 3.1.6 on 2021-03-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0029_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('text', models.TextField(blank=True, null=True)),
                ('cta', models.CharField(blank=True, max_length=100, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.CharField(blank=True, choices=[('Gold', 'Gold'), ('Silver', 'Silver')], max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
