# Generated by Django 3.1.6 on 2021-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0030_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ads'),
        ),
    ]
